server:
  port: 8060  # API Gateway port

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # Enable dynamic routing from Eureka
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"   # ✅ Use patterns, not origins
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true       # ✅ Allowed with patterns

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
